export const Images = {
    welcomeBackground: require('../images/welcomeBackground.png'),
    welcomeLogo: require('../images/welcomeLogo.png'),
    authBackground: require('../images/authBackground.png'),
    authLogo: require('../images/authLogo.png'),
    hamburger: require('../images/hamburger.png'),
    search: require('../images/search.png'),
    offerBackground: require('../images/offerBackground.png'),
    product1: require('../images/product1.png'),
    product2: require('../images/product2.png'),
    product3: require('../images/product3.png'),
    product4: require('../images/product4.png'),
    product5: require('../images/product5.png'),
    product6: require('../images/product6.png'),
    product7: require('../images/product7.png'),
    product8: require('../images/product8.png'),
    product9: require('../images/product9.png'),
    add: require('../images/add.png'),
    rightArrow: require('../images/rightArrow.png'),
    share: require('../images/share.png'),
    fav: require('../images/fav.png'),
    downArrow: require('../images/downArrow.png'),
    rArrow: require('../images/rArrow.png'),
    rating: require('../images/rating.png'),
    success: require('../images/sucess.png'),
  };
  